name: AziFly
version: @version@
main: net.azisaba.azifly.AziFly
api-version: '1.13'
description: Fly plugin for Life server
author: Azisaba Network
depend:
  - Vault
softdepend:
  - LifeTutorialAssist
commands:
  azifly:
    description: switch fly mode
    usage: /azifly [player] [seconds]
    aliases: fly
permissions:
  azifly.admin:
    description: fly without time and world limits
    default: op